#!/bin/bash
#
# Script to complete the post-install process on first torouter boot.

### BEGIN INIT INFO
# Provides:          first-run
# Default-Start:     1 2
# Required-Start:    2
# Required-Stop:
# Default-Stop:
# Short-Description: Finish torouter install on DreamPlug
### END INIT INFO

function tweak-kernel {
    # Update the kernel unless requested otherwise.

    if [ -e /var/freedombox/dont-tweak-kernel ]
    then
        rm /var/freedombox/dont-tweak-kernel
    else
        kernel_version="$(/bin/ls $mountpoint/boot/vmlinuz-*-kirkwood | sort -rn | head -n1 | sed s#$mountpoint/boot/vmlinuz-##)"

        mount -t proc proc /proc
        flash-kernel $kernel_version
        umount /proc
    fi
}

function create-keys {
    echo "Creating Keys."

    echo "(re)creating SSH keys."
    rm -f /etc/ssh/ssh_host_*
    dpkg-reconfigure openssh-server

    #echo "Need to create other keys."
    # gpg --batch --gen-key
    # see http://lists.gnupg.org/pipermail/gnupg-users/2003-March/017376.html
}

function final-configure {
    echo "Catching up on any dpkg configurations..."
    dpkg -a --configure
}

function remove-self {
    rm -f /etc/init.d/first-run
    rm -f /etc/rc1.d/S01first-run
    rm -f /etc/rc2.d/S01first-run
    rm /etc/init.d/first-run
    rm /etc/rc1.d/S01first-run
    rm /etc/rc2.d/S01first-run
}

create-keys
final-configure

# the last things we do before quitting.
#tweak-kernel
remove-self

#echo "Kernel flashed.  Rebooting."
#reboot
